name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  just_audio: ^0.9.28
  audio_service: ^0.18.7
  cached_network_image: ^3.2.1
  firebase_core: ^3.13.1
  flutter_dotenv: ^5.2.1
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
