name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  
  # UI & Storage
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Audio
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  
  # Network & Utils
  http: ^1.1.2
  js: ^0.6.7
  
  # Ek paketler
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  flutter_easyloading: ^3.0.5
  just_audio_background: ^0.0.1-beta.17
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true