name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.7.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  just_audio: ^0.9.28
  audio_service: ^0.18.7
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
